GAME_PHASE = { DAY: 0, NIGHT: 1, PENDING_START: 2 }
PLAYER_ROLE = { VILLAGER: 0, MAFIOSO: 1, DETECTIVE: 2, DOCTOR: 3 }
VILLAGER_STR = "Villager"
MAFIOSO_STR = "Mafioso"
DETECTIVE_STR = "Detective"
DOCTOR_STR = "Doctor"
ALL_ROLES = %w(VILLAGER_STR MAFIOSO_STR DETECTIVE_STR DOCTOR_STR)
